# Generated by Django 5.1.5 on 2026-08-17 17:19

import django.db.models.deletion
import pawilony.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Domyślna konfiguracja", max_length=150),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "general_units_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("45"),
                        max_digits=8,
                        verbose_name="Ogólna produkcja (pawilonów/tydzień)",
                    ),
                ),
                (
                    "hydraulic_workers",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Liczba hydraulików"
                    ),
                ),
                (
                    "welding_workers",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Liczba spawaczy"
                    ),
                ),
                (
                    "fibo_wood_workers",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Liczba os. FIBO/boazeria"
                    ),
                ),
                (
                    "hours_per_worker_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40"),
                        max_digits=6,
                        verbose_name="Godziny pracy na osobę / tydzień",
                    ),
                ),
                (
                    "safety_buffer_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15"),
                        max_digits=5,
                        verbose_name="Bufor bezpieczeństwa (%)",
                    ),
                ),
                (
                    "stale_data_warning_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Próg nieaktualności danych (godziny)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfiguracja mocy produkcyjnych",
                "verbose_name_plural": "Konfiguracje mocy produkcyjnych",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_week_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "calculated_week_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Robocza"),
                            ("CONFIRMED", "Potwierdzona"),
                            ("EXPIRED", "Wygasła"),
                            ("CANCELLED", "Anulowana"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("requested_configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rezerwacja (przyszła funkcja)",
                "verbose_name_plural": "Rezerwacje (przyszła funkcja)",
            },
        ),
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("BASE", "Produkcja ogólna"),
                            ("HYDRAULIC", "Hydraulicy"),
                            ("WELDING", "Spawacze"),
                            ("FIBO_WOOD", "FIBO / boazeria"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Brygada / centrum pracy",
                "verbose_name_plural": "Brygady / centra pracy",
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=pawilony.models.import_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VALIDATION", "Oczekuje na zatwierdzenie"),
                            ("VALIDATED", "Zwalidowany"),
                            ("COMMITTED", "Zatwierdzony"),
                            ("FAILED", "Błąd"),
                            ("REJECTED", "Odrzucony"),
                        ],
                        default="PENDING_VALIDATION",
                        max_length=30,
                    ),
                ),
                ("report", models.JSONField(blank=True, default=dict)),
                ("is_active_snapshot", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import",
                "verbose_name_plural": "Importy",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualBacklogAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_center_code",
                    models.CharField(
                        choices=[
                            ("HYDRAULIC", "Hydraulicy"),
                            ("WELDING", "Spawacze"),
                            ("FIBO_WOOD", "FIBO / boazeria"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField(verbose_name="Uzasadnienie")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ręczna korekta backlogu",
                "verbose_name_plural": "Ręczne korekty backlogu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proformas",
                        to="pawilony.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma (przyszła funkcja)",
                "verbose_name_plural": "Proformy (przyszła funkcja)",
            },
        ),
        migrations.CreateModel(
            name="OperationTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "affects_term",
                    models.BooleanField(
                        default=True,
                        help_text="Czy operacja ogranicza wyznaczany termin w MVP (False = tylko informacyjnie).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_times",
                        to="pawilony.workcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Czas operacji",
                "verbose_name_plural": "Czasy operacji",
                "ordering": ["work_center__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="PavilionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(blank=True, max_length=100)),
                ("nazwa", models.CharField(blank=True, max_length=500)),
                ("typ", models.CharField(blank=True, max_length=50)),
                ("stan_zasobow", models.CharField(blank=True, max_length=200)),
                ("ilosc_dostepna", models.CharField(blank=True, max_length=50)),
                ("jm", models.CharField(blank=True, max_length=20)),
                ("oddzial", models.CharField(blank=True, max_length=200)),
                ("rodzaj_raw", models.CharField(blank=True, max_length=200)),
                ("rodzaj_normalized", models.CharField(blank=True, max_length=200)),
                ("status_raw", models.CharField(blank=True, max_length=300)),
                ("status_normalized", models.CharField(blank=True, max_length=200)),
                (
                    "status_classification",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktywny"),
                            ("ENDED", "Zakończony"),
                            ("UNRECOGNIZED", "Nierozpoznany"),
                            ("EMPTY", "Pusty"),
                            ("CONFLICT", "Konflikt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("termin_realiz_raw", models.CharField(blank=True, max_length=200)),
                ("module_raw_text", models.CharField(blank=True, max_length=500)),
                ("module_number", models.PositiveIntegerField(blank=True, null=True)),
                ("module_present", models.BooleanField(default=False)),
                ("module_conflict", models.BooleanField(default=False)),
                ("kuchnia", models.CharField(blank=True, max_length=20)),
                ("toaleta", models.CharField(blank=True, max_length=20)),
                ("lazienka", models.CharField(blank=True, max_length=20)),
                ("prysznic", models.BooleanField(default=False)),
                ("pelna_statyka", models.BooleanField(default=False)),
                ("kratownica", models.BooleanField(default=False)),
                ("fibo", models.BooleanField(default=False)),
                ("boazeria", models.BooleanField(default=False)),
                ("stolarka_nst_raw", models.CharField(blank=True, max_length=50)),
                ("zaluzje_fasadowe_raw", models.CharField(blank=True, max_length=50)),
                ("rolety_raw", models.CharField(blank=True, max_length=50)),
                ("plyty_niestandard_raw", models.CharField(blank=True, max_length=200)),
                ("inne_niestandard_raw", models.CharField(blank=True, max_length=200)),
                ("attributes_raw", models.JSONField(blank=True, default=dict)),
                (
                    "is_counted",
                    models.BooleanField(
                        default=False, help_text="Czy liczony do aktualnego backlogu"
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="Niestandardowy — obciąża co najmniej jedną brygadę",
                    ),
                ),
                (
                    "hydraulic_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "welding_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "fibo_wood_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("conflict_reasons", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "source_row_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pavilions",
                        to="pawilony.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pawilon (migawka)",
                "verbose_name_plural": "Pawilony (migawka)",
                "indexes": [
                    models.Index(
                        fields=["import_batch", "is_counted"],
                        name="pawilony_pa_import__60a32e_idx",
                    ),
                    models.Index(
                        fields=["import_batch", "kod"],
                        name="pawilony_pa_import__48c25b_idx",
                    ),
                ],
            },
        ),
    ]
