# Generated by Django 5.1.5 on 2026-08-18 04:10
#
# Wydziela osobną pulę mocy "Niestandardowe łazienki" (WC Fibo / Premium płytki /
# Premium + boazeria) z ogólnej puli hydrauliki, zgodnie z decyzją biznesową
# (sierpień 2026) — te trzy warianty mają teraz własną, niezależną moc/przydział
# osób zamiast dzielić pulę ze standardową hydrauliką.

from decimal import Decimal
from django.db import migrations, models

CUSTOM_BATHROOM_CODES = ["toaleta_fibo", "toaleta_premium_plytki", "toaleta_premium_boazeria"]


def move_custom_wc_to_own_work_center(apps, schema_editor):
    WorkCenter = apps.get_model("pawilony", "WorkCenter")
    OperationTime = apps.get_model("pawilony", "OperationTime")

    custom_bathroom_wc, _ = WorkCenter.objects.get_or_create(
        code="CUSTOM_BATHROOM", defaults={"name": "Niestandardowe łazienki"}
    )
    OperationTime.objects.filter(code__in=CUSTOM_BATHROOM_CODES).update(work_center=custom_bathroom_wc)


def move_custom_wc_back_to_hydraulic(apps, schema_editor):
    WorkCenter = apps.get_model("pawilony", "WorkCenter")
    OperationTime = apps.get_model("pawilony", "OperationTime")

    hydraulic_wc = WorkCenter.objects.filter(code="HYDRAULIC").first()
    if hydraulic_wc:
        OperationTime.objects.filter(code__in=CUSTOM_BATHROOM_CODES).update(work_center=hydraulic_wc)


class Migration(migrations.Migration):

    dependencies = [
        ("pawilony", "0002_update_hydraulika_hours_2026_08"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacityconfiguration",
            name="custom_bathroom_workers",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Liczba os. niestandardowe łazienki"
            ),
        ),
        migrations.AddField(
            model_name="pavilionsnapshot",
            name="custom_bathroom_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="manualbacklogadjustment",
            name="work_center_code",
            field=models.CharField(
                choices=[
                    ("HYDRAULIC", "Hydraulicy"),
                    ("WELDING", "Spawacze"),
                    ("FIBO_WOOD", "FIBO / boazeria"),
                    ("CUSTOM_BATHROOM", "Niestandardowe łazienki"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workcenter",
            name="code",
            field=models.CharField(
                choices=[
                    ("BASE", "Produkcja ogólna"),
                    ("HYDRAULIC", "Hydraulicy"),
                    ("WELDING", "Spawacze"),
                    ("FIBO_WOOD", "FIBO / boazeria"),
                    ("CUSTOM_BATHROOM", "Niestandardowe łazienki"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(move_custom_wc_to_own_work_center, move_custom_wc_back_to_hydraulic),
    ]
