# Generated by Django 5.1.5 on 2026-08-18 04:25
#
# Fibo/Płytki/Boazeria przestają być zamkniętym zestawem wartości pola "Toaleta"
# (wykluczającym Standard/Komfort/Premium) — stają się niezależnymi, łączalnymi
# dodatkami, dostępnymi zarówno przy Toalecie, jak i przy Łazience (dowolny
# wariant + dowolna kombinacja dodatków). Godziny (80/100/150h) bez zmian,
# zmieniają się tylko kody/nazwy operacji, żeby odzwierciedlić nowe znaczenie.

from django.db import migrations, models

RENAMES = [
    ("toaleta_fibo", "wc_addon_fibo", "WC/łazienka: Fibo (dodatkowo)"),
    ("toaleta_premium_plytki", "wc_addon_plytki", "WC/łazienka: Płytki (dodatkowo)"),
    ("toaleta_premium_boazeria", "wc_addon_boazeria", "WC/łazienka: Boazeria (dodatkowo)"),
]


def rename_forward(apps, schema_editor):
    OperationTime = apps.get_model("pawilony", "OperationTime")
    for old_code, new_code, new_name in RENAMES:
        OperationTime.objects.filter(code=old_code).update(code=new_code, name=new_name)


def rename_backward(apps, schema_editor):
    OperationTime = apps.get_model("pawilony", "OperationTime")
    old_names = {
        "toaleta_fibo": "WC Fibo",
        "toaleta_premium_plytki": "WC Premium płytki",
        "toaleta_premium_boazeria": "WC Premium + boazeria",
    }
    for old_code, new_code, _ in RENAMES:
        OperationTime.objects.filter(code=new_code).update(code=old_code, name=old_names[old_code])


class Migration(migrations.Migration):

    dependencies = [
        ("pawilony", "0003_custom_bathroom_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="pavilionsnapshot",
            name="wc_boazeria",
            field=models.BooleanField(
                default=False, verbose_name="WC/łazienka: Boazeria (dodatkowo)"
            ),
        ),
        migrations.AddField(
            model_name="pavilionsnapshot",
            name="wc_fibo",
            field=models.BooleanField(
                default=False, verbose_name="WC/łazienka: Fibo (dodatkowo)"
            ),
        ),
        migrations.AddField(
            model_name="pavilionsnapshot",
            name="wc_plytki",
            field=models.BooleanField(
                default=False, verbose_name="WC/łazienka: Płytki (dodatkowo)"
            ),
        ),
        migrations.RunPython(rename_forward, rename_backward),
    ]
