# Generated by Django 5.1.5 on 2026-08-18 09:08
#
# Korekta z produkcją (sierpień 2026, druga tura): Fibo i Płytki NIE są osobnymi,
# doczepianymi dodatkami — ich godziny są już wliczone na stałe w warianty
# Komfort/Premium Toalety i Łazienki. Tylko Boazeria zostaje osobnym dodatkiem.
#
# Nowe godziny (baza + fibo/płytki wliczone):
#   Łazienka: Standard 7h, Komfort 10+80=90h, Premium 10+90=100h
#   Toaleta:  Standard 7h, Komfort 12+40=52h, Premium 10+45=55h

from decimal import Decimal

from django.db import migrations

NEW_TIER_HOURS = {
    "lazienka_standard": "7",
    "lazienka_komfort": "90",
    "lazienka_premium": "100",
    "toaleta_standard": "7",
    "toaleta_komfort": "52",
    "toaleta_premium": "55",
}
OLD_TIER_HOURS = {
    "lazienka_standard": "7",
    "lazienka_komfort": "10",
    "lazienka_premium": "10",
    "toaleta_standard": "7",
    "toaleta_komfort": "12",
    "toaleta_premium": "10",
}
REMOVED_ADDON_CODES = ["wc_addon_fibo", "wc_addon_plytki"]


def fold_forward(apps, schema_editor):
    OperationTime = apps.get_model("pawilony", "OperationTime")
    for code, hours in NEW_TIER_HOURS.items():
        OperationTime.objects.filter(code=code).update(hours=Decimal(hours))
    OperationTime.objects.filter(code__in=REMOVED_ADDON_CODES).delete()


def fold_backward(apps, schema_editor):
    # Nie odtwarzamy usuniętych wierszy OperationTime (Fibo/Płytki jako osobne
    # dodatki) — tylko przywracamy poprzednie godziny bazowych wariantów.
    OperationTime = apps.get_model("pawilony", "OperationTime")
    for code, hours in OLD_TIER_HOURS.items():
        OperationTime.objects.filter(code=code).update(hours=Decimal(hours))


class Migration(migrations.Migration):

    dependencies = [
        ("pawilony", "0004_wc_addons_as_independent_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pavilionsnapshot",
            name="wc_fibo",
        ),
        migrations.RemoveField(
            model_name="pavilionsnapshot",
            name="wc_plytki",
        ),
        migrations.RunPython(fold_forward, fold_backward),
    ]
